/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueRouteImport } from './routes/value'
import { Route as TrackedRouteImport } from './routes/tracked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BankrollRouteImport } from './routes/bankroll'
import { Route as AccumulatorRouteImport } from './routes/accumulator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'

const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackedRoute = TrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BankrollRoute = BankrollRouteImport.update({
  id: '/bankroll',
  path: '/bankroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AccumulatorRoute = AccumulatorRouteImport.update({
  id: '/accumulator',
  path: '/accumulator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accumulator': typeof AccumulatorRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/tracked': typeof TrackedRoute
  '/value': typeof ValueRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accumulator': typeof AccumulatorRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/tracked': typeof TrackedRoute
  '/value': typeof ValueRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accumulator': typeof AccumulatorRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/tracked': typeof TrackedRoute
  '/value': typeof ValueRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accumulator'
    | '/bankroll'
    | '/login'
    | '/tracked'
    | '/value'
    | '/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accumulator'
    | '/bankroll'
    | '/login'
    | '/tracked'
    | '/value'
    | '/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/accumulator'
    | '/bankroll'
    | '/login'
    | '/tracked'
    | '/value'
    | '/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccumulatorRoute: typeof AccumulatorRoute
  BankrollRoute: typeof BankrollRoute
  LoginRoute: typeof LoginRoute
  TrackedRoute: typeof TrackedRoute
  ValueRoute: typeof ValueRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracked': {
      id: '/tracked'
      path: '/tracked'
      fullPath: '/tracked'
      preLoaderRoute: typeof TrackedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankroll': {
      id: '/bankroll'
      path: '/bankroll'
      fullPath: '/bankroll'
      preLoaderRoute: typeof BankrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accumulator': {
      id: '/accumulator'
      path: '/accumulator'
      fullPath: '/accumulator'
      preLoaderRoute: typeof AccumulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccumulatorRoute: AccumulatorRoute,
  BankrollRoute: BankrollRoute,
  LoginRoute: LoginRoute,
  TrackedRoute: TrackedRoute,
  ValueRoute: ValueRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
